language: python
python:
  - "3.6"      # current default Python on Travis CI

matrix:
  include:
    # - sudo: required
    #   services:
    #     - docker
    #   env:
    #     - CIBW_SKIP=*manylinux1_i686*
    #     - PIP=pip
    #     - PYTHON=python
    - sudo: required
      services:
        - docker
      env:
        # - CIBW_SKIP=*manylinux1_x86_64*
        - PIP=pip3
        - PYTHON=python3
    - os: osx
      language: generic
      env:
        - PIP=pip3
        - PYTHON=python3

env:
  global:
    - TWINE_USERNAME=benfred
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel setuptools_rust
  - export CIBW_BEFORE_BUILD='$PIP install setuptools-rust && source {project}/ci/install_rust.sh'
  - export CIBW_SKIP=cp34-*\ $CIBW_SKIP
  - export CIBW_ENVIRONMENT='PATH="$HOME/rust/bin:$PATH"'
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PIP install twine
      $PYTHON -m twine upload wheelhouse/*.whl
    fi
